import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import {
  provideLucideIcons,
  LucideShoppingCart,
  LucideMenu,
  LucideX,
  LucideCheck,
  LucideStar,
  LucideDownload,
  LucideArrowRight,
  LucideZap,
  LucideShieldCheck,
  LucideQuote,
  LucideCreditCard,
  LucideHelpCircle,
  LucideMail,
  LucideChevronDown,
  LucideTarget,
  LucideLightbulb,
  LucideTrendingUp,
  LucideUsers,
  LucideBookOpen,
  LucideInfinity,
  LucideBook,
  LucideFileText,
  LucideSmartphone,
  LucideTicket,
  LucideShare2,
  LucideCamera,
  LucideBriefcase,
  LucideCircleQuestionMark,
} from '@lucide/angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideLucideIcons(
      LucideShoppingCart,
      LucideMenu,
      LucideX,
      LucideCheck,
      LucideStar,
      LucideDownload,
      LucideArrowRight,
      LucideZap,
      LucideShieldCheck,
      LucideQuote,
      LucideCreditCard,
      LucideHelpCircle,
      LucideMail,
      LucideChevronDown,
      LucideTarget,
      LucideLightbulb,
      LucideTrendingUp,
      LucideUsers,
      LucideBookOpen,
      LucideInfinity,
      LucideBook,
      LucideFileText,
      LucideSmartphone,
      LucideTicket,
      LucideShare2,
      LucideCamera,
      LucideBriefcase,
      LucideCircleQuestionMark,
    ),
  ],
};
